### PR TITLE
Allow applying vars from multiple-selector rules which include ":root"

### PR DESCRIPTION
**Pull request by mooglemoogle**
We would like to use css-vars-ponyfill to build our theme system. We would love to target our css variables against a class but we understand the issues with doing that in the ponyfill. So we have resigned to allowing class-targeted variables in css variable compliant browsers and root level variables in IE. But it seems that the library only allows us to specify variables on rules that have a single selector which is ":root". In order to support both scenarios without having duplicated themes, I've added an option to the library which bypasses the single-selector restriction and applies variables from any rule that includes ":root" as though they are only targeting ":root". Please feel free to suggest a better name, I'm not crazy about this one either but I wanted to keep it succinct.

### CODE REVIEW

**Comment by jhildenbiddle** [comment]
Hi @mooglemoogle.

Thank you for the very well done PR! Test, documentation, JSDoc updates... if every PR was like this, the world would be a better place.

My initial response is that I don't think the feature is a good fit for the ponyfill--at least not as it is currently implemented. I am happy to discuss further, but for now allow me to provide a summary of my concerns and propose some alternate paths forward. 

The current `:root`-level parsing is strict by design: it simplifies library usage by providing a subset of spec-compliant behavior, and it ensures that styles are applied consistently in both legacy and modern browsers. The proposed `allowMultiple` option is antithetical to these goals: it complicates library usage by introducing a new, non-spec-compliant behavior that results in styles being applied inconsistently in legacy and modern browsers. The result may be an acceptable compromise for your project, but it's hard to imagine others adopting it since fails to deliver on the primary goal of the ponyfill: to make legacy and modern browsers look the same when CSS custom properties are used.

Fortunately, there are alternative approaches for themeing with the ponyfill:

1. **Apply themes using [`options.variables`](https://github.com/jhildenbiddle/css-vars-ponyfill#optionsvariables)**

   Based on the example CSS you provided, it looks like you're applying themes via a class name on a container tag like `<body>`. This works for modern browsers but not for legacy browsers because neither they nor the ponyfill support scoped CSS custom properties (as you are well aware). Using `options.variables` to swap themes instead will allow you to apply theme styles consistently in all browsers, albeit with the caveat that custom properties need to be defined in JS:

   Instead of doing this:

   ```css
   .theme1 {
     --color: red;
   }

   .theme2 {
     --color: green;
   }
   ```

   Define your CSS custom properties in JS, then pass them as an object to the ponyfill:

   ```javascript
   const themes = {
     theme1: {
       '--color': 'red'
     },
     theme2: {
       '--color': 'green'
     }
   }

   // Apply a theme
   cssVars({
       variables: themes.theme1
   });
   ```

   Instruct your theme system users to define their theme customizations using `:root`-level rules so they can be applied in all browsers:

   ```html
   <!-- Custom Styles -->
   <style>
     :root {
         --color: purple;
     }
   </style>
   ```

   You can also provide both options for your users: allow projects that only support modern browsers to swap themes by applying classes to the `<body>` tag (which allows you to use scoped custom properties in your CSS), but require projects that need to support legacy browsers to swap themes via JS (e.g. `yourThemeSystemMethod('theme1')` which calls the ponyfill). The only downside to this approach is that you'll need custom properties defined in both CSS and JS, but tools like PostCSS or just a custom node script will allow you to do this pretty easily (JS => CSS).

1. **Apply themes using separate external stylesheets**

   Create separate stylesheets containing CSS custom properties for each theme:

   ```css
   /* theme1.css */
   :root {
       --color: red;
   }
   ```

   ```css
   /* theme2.css */
   :root {
       --color: green;
   }
   ```

   Create a shared CSS file with all styles that will be hydrated by one of the above theme files:

   ```css
   /* app.css */
   p {
       color: var(--color);
   }
   ```

   Link to both the common CSS and one of the theme files, then run the ponyfill for legacy browsers:

   ```html
   <link rel="stylesheet" href="common.css">
   <link rel="stylesheet" href="theme1.css">
   ```

   To apply a new theme, swap out `theme1.css` for `theme2.css`. 
   
   You can further optimize this setup by using a CSS preprocessor to generate separate files for each theme that merge the common CSS with theme variables. For example, you would generate `theme1-bundle.css` which combines `app.css` and `theme1.css`. This reduces the number of `<link>` elements required at the expense of each theme file containing the same common CSS. Take a look at [docsify-themeable](https://jhildenbiddle.github.io/docsify-themeable/) to get an idea how this can be done.

1. **Mimic `allowMultiple` behavior by avoiding selector lists**

   If you want the behavior `allowMultiple` provides but prefer to use a non-forked version of the ponyfill, you can accomplish the same thing simply by not using selector lists. You can automate duplication of the custom properties into separate rules using a CSS processor like Sass or PostCSS:

   **SCSS**

   ```scss
   @mixin theme1 {
       --color: red;
   }

   :root {
       @include theme1;
   }
   .theme1 {
       @include theme1;
   }
   ```

   **PostCSS + [postcss-extend-rule plugin](https://www.npmjs.com/package/postcss-extend-rule)**

   ```css
   %theme1 {
       --color: red;
   }

   :root {
       @extend theme1;
   }
   .theme1 {
       @extend theme1;
   }
   ```

   The downside with this approach is the custom property declarations are repeated for each theme, but after taking gzip compression into account the real-world difference in file size will likely be negligible. If that's hard to believe, check for yourself using the network tab of your browser's developer tools.

I'm not familiar enough with your theme system to know if any of these approaches are viable, but I wanted to offer them as they have been used by others to work with the limitations of the ponyfill. The important difference between the first two approachs and the one offered by the `allowMultiple` option is that they allow both modern and legacy browsers to be styled the same way. The third approach is just a way to accomplish the same thing as `allowMultiple` without requiring changes to the ponyfill.

Hope this helps.

**Comment by jhildenbiddle** [comment]
Hey again, @mooglemoogle.

I haven't heard back so I'm going to close the PR. If you'd like to discuss further, please feel free to create an issue.

Thanks again for taking the time to create the PR.

**Comment by mooglemoogle** [comment]
Thanks! I appreciate the time you took in your answer and I'm sorry i haven't responded yet, I've been off work all this week. I can appreciate that this functionality doesn't fit with your view for the library. Your suggestions are much appreciated but I don't think they'll allow us to accomplish the design we have. We may rethink the design a bit to accommodate your suggestions or just continue to use the fork. We'll talk it over this coming week.

Thanks again!

**Comment by jhildenbiddle** [comment]
Sounds good. Happy to help if you have any questions.

**Pull request closed without merging**
